version: "3.9"
services: 
    # MySQL
    db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - 3307:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        MYSQL_DATABASE: kampus_merdeka
      # healthcheck:
      #   test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      #   interval: 2s
      #   timeout: 20s
      #   retries: 10

    adminer:
      image: adminer
      restart: always
      ports:
        - 9191:8080
    
    app:
      container_name: api_kampus_merdeka
      build: .
      restart: always
      ports: 
        - 8080:8080
      volumes:
        - .:/usr/src/app/
      # depends_on:
      #   db:
      #   condition: service_healthy
      # environment:
      #   - WAIT_HOSTS=db:3306
      #   - WAIT_HOSTS_TIMEOUT=300
      #   - WAIT_SLEEP_INTERVAL=30
      #   - WAIT_HOST_CONNECT_TIMEOUT=30